name: deploy-landing
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node (if tooling exists)
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install deps (optional)
        run: |
          if [ -f package.json ]; then npm ci; fi
      - name: Build (optional)
        run: |
          if [ -f package.json ]; then npm run build || true; fi
      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_SWA_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"
          output_location: "/"
      - name: Lighthouse smoke test
        uses: treosh/lighthouse-ci-action@v11
        with:
          urls: |
            https://simiriki.com
          configPath: ./lighthouserc.json
          uploadArtifacts: true
          temporaryPublicStorage: true
