name: link-check
on:
  schedule:
    - cron: "41 2 * * *"
  workflow_dispatch:
jobs:
  lychee:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Link Checker
        uses: lycheeverse/lychee-action@v1
        with:
          args: --verbose --no-progress --max-concurrency 8 --exclude-mail --accept 200,206,429,403 .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
