name: Site — GitHub Pages
on:
  push: { branches: [main] }
  workflow_dispatch: {}
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: 'pages'
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Prepare artifact (copy -> dist)
        run: |
          rm -rf dist
          mkdir -p dist
          rsync -a --delete \
            --exclude 'dist' \
            --exclude '.git' \
            --exclude '.github' \
            --exclude 'node_modules' \
            ./ dist/
      - uses: actions/upload-pages-artifact@v3
        with: { path: ./dist }
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
